In [4]:
%pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
df = pd.read_excel("data/GSAF5.xls")

In [2]:
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [4]:
df.columns = df.columns.str.lower()
df.columns

Index(['date', 'year', 'type', 'country', 'state', 'location', 'activity',
       'name', 'sex', 'age', 'injury', 'fatal y/n', 'time', 'species ',
       'source', 'pdf', 'href formula', 'href', 'case number', 'case number.1',
       'original order', 'unnamed: 21', 'unnamed: 22'],
      dtype='object')

In [5]:
df = df[['country', 'activity', 'type', 'year', 'species ', 'fatal y/n']]
df.head()

,country,activity,type,year,species,fatal y/n
0,Maldives,Swimming,UNprovoked,2026.0,Unknown,N
1,Australia,Surfing,Unprovoked,2026.0,Bronze Whaler,N
2,Bahamas,Swimming,Unprovoked,2026.0,Unknown,N
3,Australia,Diving,Unprovoked,2026.0,Great White Shark 3.5m (11.5ft),N
4,Australia,Surfing,Unprovoked,2026.0,Unknown,N

## Revisión de null

In [6]:
df.isnull().sum()

country        50
activity      583
type           18
year            2
species      3131
fatal y/n     561
dtype: int64

In [7]:
df = df.dropna(subset=['country', 'activity', 'type'])

## Revisión de duplicados

In [8]:
df.duplicated().sum()

np.int64(573)

In [9]:
df = df.drop_duplicates()

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['activity'].head(10)

0         Swimming
1          Surfing
2         Swimming
3           Diving
4          Surfing
5          Surfing
6         Swimming
7    Wing Foiling
8       Snorkeling
9    Wing Foiling
Name: activity, dtype: object

In [12]:
def clean_activity(activity):
    activity = str(activity).lower()
    
    if 'surf' in activity:
        return 'Surfing'
    elif 'swim' in activity or 'bathing' in activity or 'floating' in activity:
        return 'Swimming'
    elif 'wading' in activity or 'standing' in activity or 'treading' in activity:
        return 'Shallow water'
    elif 'div' in activity:
        return 'Diving'
    elif 'fish' in activity:
        return 'Fishing'
    elif 'snorkel' in activity:
        return 'Snorkeling'
    elif 'board' in activity:
        return 'Board sports'
    else:
        return 'Other'

In [13]:
df['activity_clean'] = df['activity'].apply(clean_activity)

In [14]:
df['activity_clean'].value_counts()

activity_clean
Swimming         1350
Fishing          1202
Surfing          1128
Other             822
Diving            600
Shallow water     358
Board sports      279
Snorkeling        135
Name: count, dtype: int64

#Se agruparon las actividades en categorías principales y se mantuvo una categoría ‘Other’ para casos menos frecuentes o difíciles de clasificar

In [15]:
df_unprovoked = df[df['type'] == 'Unprovoked'].copy()

In [16]:
df_unprovoked.head()

,country,activity,type,year,species,fatal y/n,activity_clean
1,Australia,Surfing,Unprovoked,2026.0,Bronze Whaler,N,Surfing
2,Bahamas,Swimming,Unprovoked,2026.0,Unknown,N,Swimming
3,Australia,Diving,Unprovoked,2026.0,Great White Shark 3.5m (11.5ft),N,Diving
4,Australia,Surfing,Unprovoked,2026.0,Unknown,N,Surfing
5,USA,Surfing,Unprovoked,2026.0,Great White Shark,N,Surfing